name: Telegram Bot

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Java dependencies
        uses: actions/setup-java@v3
        with:
          java-version: 17

      - name: Install the ChatGPT API client
        run: mvn install:install-file -Dfile=chatgpt-java-<version>.jar -DgroupId=com.github.gr1228 -DartifactId=chatgpt-java -Dversion=<version>

      - name: Start the Telegram bot
        run: java -jar bot.jar
