name: Telegram Bot

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Python 3.10
  uses: actions/setup-python@v3
  with:
    python-version: 3.10
    
      - name: Install Python dependencies
        uses: actions/setup-python@v3
        with:
          python-version: 3.10

      - name: Install the ChatGPT API client
        run: pip install chatgpt

      - name: Start the Telegram bot
        run: python bot.py
